### ISSUE TITLE
Need a way to submit codes through Named Session instead of Session ID numbers

### ISSUE THREAD

**Issue by prabhu1984** [cloudera/livy#17]
https://issues.cloudera.org/browse/LIVY-41

Hi, can someone please help us on this issue?

We are looking to submit codes through session_name instead of ids.

**Comment by harishreedharan** [comment]
Session names would not be unique. Is there a reason you can't use session ids?

**Comment by ksakellis** [comment]
Please track this issue on the JIRA.
