### ISSUE TITLE
Does livy support spark with sqlContext?

### ISSUE THREAD

**Issue by jamartinh** [cloudera/livy#35]
rajeshbalamohan commented on 10 Dec 2015
-Launched livy-yarn-server
-Was able to create spark job via livy

"sc.toString()" works fine, but "sqlContext.toString()" is not getting loaded. Is there anything specific to be done in config for accessing sqlContext?

**Comment by jamartinh** [comment]
Hi, I am suffering the same issue.

I use Spark 1.6.0, I use this spark distro with Hive perfect, from pyspark.
but from the Hue Notebooks through livy-server I get:

Traceback (most recent call last): Exception: ("You must build Spark with Hive. Export 'SPARK_HIVE=true' and run build/sbt assembly", Py4JJavaError(u'An error occurred while calling None.org.apache.spark.sql.hive.HiveContext.\n', JavaObject id=o51))

**Comment by jamartinh** [comment]
I am able to import HiveContext, create one etc... but
print(hc)
hc.tableNames() gives me that error.

Best,
jose

**Comment by jamartinh** [comment]
In particular, see the three warnigs about SparkSQL

[INFO] ------------------------------------------------------------------------
[INFO] Building livy-server_2.10 0.2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ livy-server_2.10 ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ livy-server_2.10 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:compile (default) @ livy-server_2.10 ---
[WARNING] Zinc server is not available at port 3030 - reverting to normal incremental compile
[INFO] Using incremental compilation
[INFO] Compiling 5 Scala sources to /data/livy-server/livy/server/target/classes...
[INFO]
[INFO] --- maven-antrun-plugin:1.8:run (create-tmp-dir) @ livy-server_2.10 ---
[INFO] Executing tasks

main:
    [mkdir] Created dir: /data/livy-server/livy/server/target/tmp
[INFO] Executed tasks
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ livy-server_2.10 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:testCompile (default) @ livy-server_2.10 ---
[WARNING] Zinc server is not available at port 3030 - reverting to normal incremental compile
[INFO] Using incremental compilation
[INFO] Compiling 4 Scala sources to /data/livy-server/livy/server/target/test-classes...
[WARNING] Class org.apache.spark.sql.SQLContext not found - continuing with a stub.
[WARNING] Class org.apache.spark.sql.hive.HiveContext not found - continuing with a stub.
[WARNING] Class org.apache.spark.streaming.api.java.JavaStreamingContext not found - continuing with a stub.
[WARNING] three warnings found
[INFO]
[INFO] --- maven-surefire-plugin:2.19:test (default-test) @ livy-server_2.10 ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ livy-server_2.10 ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.3.2:jar (default-jar) @ livy-server_2.10 ---
[INFO] Building jar: /data/livy-server/livy/server/target/livy-server_2.10-0.2.0-SNAPSHOT.jar
[INFO]

**Comment by ksakellis** [comment]
If this problem persists, please file a jira here: https://issues.cloudera.org/projects/LIVY.
